name: Build Executables

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name=PythonInstaller-Windows python_installer.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/PythonInstaller-Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name=PythonInstaller-macOS python_installer.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-executable
        path: dist/PythonInstaller-macOS

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name=PythonInstaller-Linux python_installer.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-executable
        path: dist/PythonInstaller-Linux
